version: "3.9"
services:
  go:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../../:/app
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superuser
      - POSTGRES_DB=rradar
    ports:
      - 5432:5432
